### ISSUE TITLE
Interactive mode and future

### ISSUE THREAD

**Issue by adambajguz** [adambajguz/Typin#1]
Hi @jim-wilson-kt, 
hope you got a notification and you are now reading this issue. I have decided to create a new library based on [CliFx](https://github.com/Tyrrrz/CliFx/tree/master/CliFx) source code, since my fork and previous pull request were changing CliFx too much in a very different direction.

I've thought that you might be interested to test the lib and maybe contribute with code or some ideas. 

Typin is currently published as a preview version on NuGet. In the next days I will probably list everything that I want to be done before releasing version 1.0 to NuGet. My plan is to finish v1.0 to the end of August.

**Comment by jim-wilson-kt** [comment]
Adam,

Yes, I did receive the notification. The functionality you added looks very useful. I understand the reasons why Alexey was reluctant to accept your pull request. There were lots of changes and many of them were extensive.

I have tested what you provided. I can help with documentation. My schedule is very busy through Friday. I plan to look it over again during the weekend.

--Jim
