### ISSUE TITLE
Interactive mode executes the command line arguments at every new commands

### ISSUE THREAD

**Issue by phito** [adambajguz/Typin#208]
When providing statup arguments to the executable while using interactive mode, the startup command is executed after every new command issued.

I think it is just a matter of setting the "firstEnter" flag in InteractiveMode.cs to false right after this line

https://github.com/adambajguz/Typin/blob/master/src/Typin/Typin/Modes/Interactive/InteractiveMode.cs#L61

**Comment by phito** [comment]
that was super fast, cheers! 👏

**Comment by adambajguz** [comment]
@phito Typin 3.0.4 with the fix should be available in about 5 minutes
